# Generated by Django 6.0.5 on 2026-06-02 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('vacunacion', 'Vacunación'), ('desparasitacion', 'Desparasitación'), ('revision', 'Revisión'), ('otro', 'Otro')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='animals.animal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
